// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://txhokwtfcpdqtiyviwdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4aG9rd3RmY3BkcXRpeXZpd2RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzMzY2MTksImV4cCI6MjA4MTkxMjYxOX0.Rxx8or96QOeHepFJXzxn15CA_mzzUJXGqnOB79W8TUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);